#ifndef FILESCHEMAPLUGIN_GLOBAL_H
#define FILESCHEMAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILESCHEMAPLUGIN_LIBRARY)
#  define FILESCHEMAPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define FILESCHEMAPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FILESCHEMAPLUGIN_GLOBAL_H
